require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'config/environments/*'
  SuggestExtensions: false

Rails:
  Enabled: true

Performance:
  Enabled: true

Style/Documentation:
  Enabled: false
