require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'config/environments/*'
    - 'app/services/question_generator_service.rb'
    - 'app/test/api_stubs/*'
  SuggestExtensions: false

Rails:
  Enabled: true

Performance:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 140

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 25 

Metrics/BlockLength:
  Max: 120

Metrics/ModuleLength:
  Max: 150

Rails/ThreeStateBooleanColumn:
  Enabled: false 

Style/OpenStructUse:
  Enabled: false